# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: Azure Pipelines
  demands: maven

variables:
  SPRING_PROFILES_ACTIVE: 'prod'
  DB_URL: 'jdbc:postgresql://sniff-db.postgres.database.azure.com:5432/sniff_db?sslmode=require'
  DB_LOGIN: 'sniff_admin'
  DB_PASSWORD: 'n9s77CZjnpktJHD'

steps:
- task: Maven@4
  displayName: 'Maven pom.xml'
  inputs:
    options: '-Dspring.profiles.active=$(SPRING_PROFILES_ACTIVE) -Dspring.datasource.url=$(DB_URL) -Dspring.datasource.username=$(DB_LOGIN) -Dspring.datasource.password=$(DB_PASSWORD)'
    jdkVersionOption: 1.17
    mavenOptions: '-Xmx1024m '
  env:
    SPRING_PROFILES_ACTIVE: $(SPRING_PROFILES_ACTIVE)
    DB_URL: $(DB_URL)
    DB_LOGIN: $(DB_LOGIN)
    DB_PASSWORD: $(DB_PASSWORD)

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
